version: '3.8'
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  react-blue:
    container_name: react-blue
    build: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`localhost`)"
      - "traefik.http.routers.react.entrypoints=web"
      - "traefik.http.services.react.loadbalancer.server.port=80"
    restart: unless-stopped


  react-green:
    container_name: react-green
    build: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.react-green.loadbalancer.server.port=80"
    restart: unless-stopped
