version: '3.8'
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik_load_balancer
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  react-blue:
    build: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-blue.rule=Host(`votre-domaine.com`)"
      - "traefik.http.routers.react-blue.entrypoints=web"
      - "traefik.http.services.react-blue.loadbalancer.server.port=80"
    restart: unless-stopped

  react-green:
    build: ./app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-green.rule=Host(`votre-domaine.com`) && PathPrefix(`/green`)"
      - "traefik.http.routers.react-green.entrypoints=web"
      - "traefik.http.services.react-green.loadbalancer.server.port=80"
    restart: unless-stopped